name:                cswk-gambit-two
version:             0.1.0.0
license:             BSD3
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2023 Alex Dixon"

dependencies:
- base >= 4.7 && < 5
- megaparsec
- filepath
- process
- text
- split
- parsec
- void



ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans 
- -Wno-missing-export-lists

language: GHC2021

default-extensions:
- StrictData
- LambdaCase



library:
  source-dirs: src
  

executables:
  gambit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cswk-gambit-two